// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/court.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourtType int32

const (
	CourtType_OUTDOOR CourtType = 0
	CourtType_GYM     CourtType = 1
)

// Enum value maps for CourtType.
var (
	CourtType_name = map[int32]string{
		0: "OUTDOOR",
		1: "GYM",
	}
	CourtType_value = map[string]int32{
		"OUTDOOR": 0,
		"GYM":     1,
	}
)

func (x CourtType) Enum() *CourtType {
	p := new(CourtType)
	*p = x
	return p
}

func (x CourtType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CourtType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_court_proto_enumTypes[0].Descriptor()
}

func (CourtType) Type() protoreflect.EnumType {
	return &file_proto_court_proto_enumTypes[0]
}

func (x CourtType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CourtType.Descriptor instead.
func (CourtType) EnumDescriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{0}
}

type CourtStatus int32

const (
	CourtStatus_EMPTY               CourtStatus = 0
	CourtStatus_WAITING_FOR_PLAYERS CourtStatus = 1
	CourtStatus_PACKED              CourtStatus = 2
)

// Enum value maps for CourtStatus.
var (
	CourtStatus_name = map[int32]string{
		0: "EMPTY",
		1: "WAITING_FOR_PLAYERS",
		2: "PACKED",
	}
	CourtStatus_value = map[string]int32{
		"EMPTY":               0,
		"WAITING_FOR_PLAYERS": 1,
		"PACKED":              2,
	}
)

func (x CourtStatus) Enum() *CourtStatus {
	p := new(CourtStatus)
	*p = x
	return p
}

func (x CourtStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CourtStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_court_proto_enumTypes[1].Descriptor()
}

func (CourtStatus) Type() protoreflect.EnumType {
	return &file_proto_court_proto_enumTypes[1]
}

func (x CourtStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CourtStatus.Descriptor instead.
func (CourtStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{1}
}

type Court struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float32                `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	HoopCount     int32                  `protobuf:"varint,7,opt,name=hoop_count,json=hoopCount,proto3" json:"hoop_count,omitempty"`
	CourtType     CourtType              `protobuf:"varint,8,opt,name=court_type,json=courtType,proto3,enum=court.CourtType" json:"court_type,omitempty"`
	Status        CourtStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=court.CourtStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Court) Reset() {
	*x = Court{}
	mi := &file_proto_court_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Court) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Court) ProtoMessage() {}

func (x *Court) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Court.ProtoReflect.Descriptor instead.
func (*Court) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{0}
}

func (x *Court) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Court) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Court) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Court) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Court) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Court) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Court) GetHoopCount() int32 {
	if x != nil {
		return x.HoopCount
	}
	return 0
}

func (x *Court) GetCourtType() CourtType {
	if x != nil {
		return x.CourtType
	}
	return CourtType_OUTDOOR
}

func (x *Court) GetStatus() CourtStatus {
	if x != nil {
		return x.Status
	}
	return CourtStatus_EMPTY
}

func (x *Court) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	HoopCount     int32                  `protobuf:"varint,6,opt,name=hoop_count,json=hoopCount,proto3" json:"hoop_count,omitempty"`
	CourtType     CourtType              `protobuf:"varint,7,opt,name=court_type,json=courtType,proto3,enum=court.CourtType" json:"court_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourtRequest) Reset() {
	*x = CreateCourtRequest{}
	mi := &file_proto_court_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourtRequest) ProtoMessage() {}

func (x *CreateCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourtRequest.ProtoReflect.Descriptor instead.
func (*CreateCourtRequest) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourtRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCourtRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateCourtRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateCourtRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateCourtRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateCourtRequest) GetHoopCount() int32 {
	if x != nil {
		return x.HoopCount
	}
	return 0
}

func (x *CreateCourtRequest) GetCourtType() CourtType {
	if x != nil {
		return x.CourtType
	}
	return CourtType_OUTDOOR
}

type GetCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourtRequest) Reset() {
	*x = GetCourtRequest{}
	mi := &file_proto_court_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourtRequest) ProtoMessage() {}

func (x *GetCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourtRequest.ProtoReflect.Descriptor instead.
func (*GetCourtRequest) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{2}
}

func (x *GetCourtRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCourtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`                                // filter by city, empty = all
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // only WAITING or PACKED courts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourtsRequest) Reset() {
	*x = ListCourtsRequest{}
	mi := &file_proto_court_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourtsRequest) ProtoMessage() {}

func (x *ListCourtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourtsRequest.ProtoReflect.Descriptor instead.
func (*ListCourtsRequest) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{3}
}

func (x *ListCourtsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListCourtsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListCourtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courts        []*Court               `protobuf:"bytes,1,rep,name=courts,proto3" json:"courts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourtsResponse) Reset() {
	*x = ListCourtsResponse{}
	mi := &file_proto_court_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourtsResponse) ProtoMessage() {}

func (x *ListCourtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourtsResponse.ProtoReflect.Descriptor instead.
func (*ListCourtsResponse) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{4}
}

func (x *ListCourtsResponse) GetCourts() []*Court {
	if x != nil {
		return x.Courts
	}
	return nil
}

type UpdateCourtStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourtId       int32                  `protobuf:"varint,1,opt,name=court_id,json=courtId,proto3" json:"court_id,omitempty"`
	Status        CourtStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=court.CourtStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourtStatusRequest) Reset() {
	*x = UpdateCourtStatusRequest{}
	mi := &file_proto_court_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourtStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourtStatusRequest) ProtoMessage() {}

func (x *UpdateCourtStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourtStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourtStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCourtStatusRequest) GetCourtId() int32 {
	if x != nil {
		return x.CourtId
	}
	return 0
}

func (x *UpdateCourtStatusRequest) GetStatus() CourtStatus {
	if x != nil {
		return x.Status
	}
	return CourtStatus_EMPTY
}

type DeleteCourtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourtRequest) Reset() {
	*x = DeleteCourtRequest{}
	mi := &file_proto_court_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourtRequest) ProtoMessage() {}

func (x *DeleteCourtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourtRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourtRequest) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCourtRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCourtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourtResponse) Reset() {
	*x = DeleteCourtResponse{}
	mi := &file_proto_court_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourtResponse) ProtoMessage() {}

func (x *DeleteCourtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_court_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourtResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourtResponse) Descriptor() ([]byte, []int) {
	return file_proto_court_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourtResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_court_proto protoreflect.FileDescriptor

const file_proto_court_proto_rawDesc = "" +
	"\n" +
	"\x11proto/court.proto\x12\x05court\"\xae\x02\n" +
	"\x05Court\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x02R\tlongitude\x12\x1d\n" +
	"\n" +
	"hoop_count\x18\a \x01(\x05R\thoopCount\x12/\n" +
	"\n" +
	"court_type\x18\b \x01(\x0e2\x10.court.CourtTypeR\tcourtType\x12*\n" +
	"\x06status\x18\t \x01(\x0e2\x12.court.CourtStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xe0\x01\n" +
	"\x12CreateCourtRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x02R\tlongitude\x12\x1d\n" +
	"\n" +
	"hoop_count\x18\x06 \x01(\x05R\thoopCount\x12/\n" +
	"\n" +
	"court_type\x18\a \x01(\x0e2\x10.court.CourtTypeR\tcourtType\"!\n" +
	"\x0fGetCourtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"H\n" +
	"\x11ListCourtsRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\":\n" +
	"\x12ListCourtsResponse\x12$\n" +
	"\x06courts\x18\x01 \x03(\v2\f.court.CourtR\x06courts\"a\n" +
	"\x18UpdateCourtStatusRequest\x12\x19\n" +
	"\bcourt_id\x18\x01 \x01(\x05R\acourtId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.court.CourtStatusR\x06status\"$\n" +
	"\x12DeleteCourtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x13DeleteCourtResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*!\n" +
	"\tCourtType\x12\v\n" +
	"\aOUTDOOR\x10\x00\x12\a\n" +
	"\x03GYM\x10\x01*=\n" +
	"\vCourtStatus\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x17\n" +
	"\x13WAITING_FOR_PLAYERS\x10\x01\x12\n" +
	"\n" +
	"\x06PACKED\x10\x022\xc5\x02\n" +
	"\fCourtService\x126\n" +
	"\vCreateCourt\x12\x19.court.CreateCourtRequest\x1a\f.court.Court\x120\n" +
	"\bGetCourt\x12\x16.court.GetCourtRequest\x1a\f.court.Court\x12A\n" +
	"\n" +
	"ListCourts\x12\x18.court.ListCourtsRequest\x1a\x19.court.ListCourtsResponse\x12B\n" +
	"\x11UpdateCourtStatus\x12\x1f.court.UpdateCourtStatusRequest\x1a\f.court.Court\x12D\n" +
	"\vDeleteCourt\x12\x19.court.DeleteCourtRequest\x1a\x1a.court.DeleteCourtResponseB\x1bZ\x19court-service/proto;protob\x06proto3"

var (
	file_proto_court_proto_rawDescOnce sync.Once
	file_proto_court_proto_rawDescData []byte
)

func file_proto_court_proto_rawDescGZIP() []byte {
	file_proto_court_proto_rawDescOnce.Do(func() {
		file_proto_court_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_court_proto_rawDesc), len(file_proto_court_proto_rawDesc)))
	})
	return file_proto_court_proto_rawDescData
}

var file_proto_court_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_court_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_court_proto_goTypes = []any{
	(CourtType)(0),                   // 0: court.CourtType
	(CourtStatus)(0),                 // 1: court.CourtStatus
	(*Court)(nil),                    // 2: court.Court
	(*CreateCourtRequest)(nil),       // 3: court.CreateCourtRequest
	(*GetCourtRequest)(nil),          // 4: court.GetCourtRequest
	(*ListCourtsRequest)(nil),        // 5: court.ListCourtsRequest
	(*ListCourtsResponse)(nil),       // 6: court.ListCourtsResponse
	(*UpdateCourtStatusRequest)(nil), // 7: court.UpdateCourtStatusRequest
	(*DeleteCourtRequest)(nil),       // 8: court.DeleteCourtRequest
	(*DeleteCourtResponse)(nil),      // 9: court.DeleteCourtResponse
}
var file_proto_court_proto_depIdxs = []int32{
	0,  // 0: court.Court.court_type:type_name -> court.CourtType
	1,  // 1: court.Court.status:type_name -> court.CourtStatus
	0,  // 2: court.CreateCourtRequest.court_type:type_name -> court.CourtType
	2,  // 3: court.ListCourtsResponse.courts:type_name -> court.Court
	1,  // 4: court.UpdateCourtStatusRequest.status:type_name -> court.CourtStatus
	3,  // 5: court.CourtService.CreateCourt:input_type -> court.CreateCourtRequest
	4,  // 6: court.CourtService.GetCourt:input_type -> court.GetCourtRequest
	5,  // 7: court.CourtService.ListCourts:input_type -> court.ListCourtsRequest
	7,  // 8: court.CourtService.UpdateCourtStatus:input_type -> court.UpdateCourtStatusRequest
	8,  // 9: court.CourtService.DeleteCourt:input_type -> court.DeleteCourtRequest
	2,  // 10: court.CourtService.CreateCourt:output_type -> court.Court
	2,  // 11: court.CourtService.GetCourt:output_type -> court.Court
	6,  // 12: court.CourtService.ListCourts:output_type -> court.ListCourtsResponse
	2,  // 13: court.CourtService.UpdateCourtStatus:output_type -> court.Court
	9,  // 14: court.CourtService.DeleteCourt:output_type -> court.DeleteCourtResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_court_proto_init() }
func file_proto_court_proto_init() {
	if File_proto_court_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_court_proto_rawDesc), len(file_proto_court_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_court_proto_goTypes,
		DependencyIndexes: file_proto_court_proto_depIdxs,
		EnumInfos:         file_proto_court_proto_enumTypes,
		MessageInfos:      file_proto_court_proto_msgTypes,
	}.Build()
	File_proto_court_proto = out.File
	file_proto_court_proto_goTypes = nil
	file_proto_court_proto_depIdxs = nil
}
